from __future__ import annotations

try:
    from tests.support import (
        Any,
        DashboardFixtureMixin,
        ROOT,
        dashboard_asset_bundle,
        load_module,
        unittest,
    )
except ModuleNotFoundError:
    from support import (
        Any,
        DashboardFixtureMixin,
        ROOT,
        dashboard_asset_bundle,
        load_module,
        unittest,
    )

class DashboardCleanupUiTests(DashboardFixtureMixin, unittest.TestCase):
    LEGACY_CLEANUP_ROW_FIELDS = {
        "retention_role",
        "retention_impact",
        "delete_all_impact",
        "retention_summary",
        "delete_all_summary",
    }

    def assert_cleanup_row_uses_display_contract(self, row: dict[str, Any]) -> None:
        self.assertTrue(self.LEGACY_CLEANUP_ROW_FIELDS.isdisjoint(row))
        self.assertIn("display", row)
        self.assertIn("delete_all_display", row)
        for display in (row["display"], row["delete_all_display"]):
            if "action" in display:
                self.assertEqual(set(display.get("action_file_counts", {})), {"Delete", "Rewrite", "Rebuild"})

    def test_log_cleanup_page_contract(self) -> None:
        source = dashboard_asset_bundle()
        self.assertIn('<button class="nav-btn" data-view-target="cleanup">Cleanup</button>', source)
        self.assertIn("const views = new Set(['overview', 'turns', 'tools', 'subagents', 'cleanup']);", source)
        self.assertIn('<section id="cleanup" class="view" data-view="cleanup">', source)
        self.assertIn('class="panel cleanup-workbench-panel"', source)
        self.assertIn('class="panel cleanup-files-panel"', source)
        self.assertNotIn('class="panel cleanup-detail-panel"', source)
        self.assertIn('<h2 id="cleanup-detail-modal-title">File Detail</h2>', source)
        self.assertNotIn('id="cleanup-file-detail"', source)
        self.assertIn('id="cleanup-detail-modal"', source)
        self.assertIn('id="cleanup-detail-modal-body"', source)
        self.assertNotIn('id="cleanup-detail-modal-subtitle"', source)
        self.assertNotIn('class="panel cleanup-overview-panel"', source)
        self.assertIn('id="cleanup-refresh"', source)
        self.assertIn('id="cleanup-delete"', source)
        self.assertIn('<button id="cleanup-delete" class="danger" type="button">Delete Logs</button>', source)
        self.assertIn("button.danger { color: var(--primary-text); border-color: var(--danger); background: var(--danger); }", source)
        self.assertIn(':root[data-theme="dark"] button.danger {', source)
        self.assertIn("color: var(--button-danger-text);\n      border-color: var(--button-danger-border);\n      background: var(--button-danger-bg);", source)
        self.assertIn("Delete", source)
        self.assertIn("Delete</button>", source)
        self.assertIn("<h2>Cleanup</h2>", source)
        self.assertNotIn("<h2>Log Cleanup</h2>", source)
        self.assertNotIn("<span class=\"hint\">cutoff date</span>", source)
        self.assertIn("<h2>Retention Impact</h2>", source)
        self.assertIn("<span class=\"hint\">Service-managed files</span>", source)
        self.assertNotIn("cleanup-retention-copy", source)
        self.assertNotIn("Deletes raw log rows older than the selected range", source)
        self.assertIn('id="cleanup-selected-bytes"', source)
        self.assertIn('id="cleanup-selected-count"', source)
        self.assertIn('class="cleanup-retention-presets"', source)
        self.assertIn('data-cleanup-retention-preset="1"', source)
        self.assertIn('data-cleanup-retention-preset="7"', source)
        self.assertIn('data-cleanup-retention-preset="14"', source)
        self.assertIn('data-cleanup-retention-preset="30"', source)
        self.assertIn('data-cleanup-retention-preset="90"', source)
        self.assertIn('data-cleanup-retention-preset="all"', source)
        self.assertNotIn('class="cleanup-all-option"', source)
        self.assertNotIn('class="cleanup-all-data-button"', source)
        self.assertNotIn(">All Data</button>", source)
        self.assertNotIn("Delete All Data", source)
        self.assertIn("Delete Logs", source)
        self.assertIn("Delete All Logs", source)
        self.assertIn(">All Logs</button>", source)
        self.assertNotIn(">ALL</button>", source)
        self.assertLess(source.index('data-cleanup-retention-preset="all"'), source.index('data-cleanup-retention-preset="1"'))
        self.assertNotIn('data-cleanup-retention-preset="custom"', source)
        self.assertNotIn(">Custom</button>", source)
        self.assertIn('id="cleanup-retention-custom"', source)
        self.assertIn('id="cleanup-retention-date"', source)
        self.assertIn('id="cleanup-retention-custom-state"', source)
        self.assertIn('id="cleanup-retention-files"', source)
        self.assertIn('id="cleanup-confirm-modal"', source)
        self.assertNotIn('<button id="cleanup-confirm-close"', source)
        self.assertIn("document.getElementById('cleanup-confirm-close')?.addEventListener", source)
        self.assertIn("function confirmCleanupAction({title, subtitle, body, confirmLabel})", source)
        self.assertIn("function resolveCleanupConfirmModal(result = false)", source)
        self.assertIn("function setCleanupConfirmProgress({message, detail = '', step = 1, total = 3, tone = 'busy', done = false, progressPercent = null})", source)
        self.assertIn("function retentionDeleteConfirmBody()", source)
        self.assertIn("function allDataDeleteConfirmBody()", source)
        self.assertIn("function isServiceBusyError(err)", source)
        self.assertIn("function emptyCleanupRetention()", source)
        self.assertIn("state.cleanupRetentionAvailable = false;", source)
        self.assertIn("disableCleanupAction('Preview unavailable');", source)
        self.assertIn('class="cleanup-retention-form cleanup-control-row"', source)
        self.assertIn('type="date"', source)
        self.assertIn("Older Than", source)
        self.assertNotIn("Delete Scope", source)
        self.assertIn("Delete Before", source)
        self.assertLess(source.index('id="cleanup-retention-custom"'), source.index('class="cleanup-option"'))
        self.assertIn(".cleanup-retention-form {\n      display: flex;\n      align-items: center;\n      gap: 8px;\n      flex: 0 0 auto;\n      min-width: 0;\n      min-height: 76px;\n      padding: 18px 16px;", source)
        self.assertNotIn(".cleanup-action-status:empty::before", source)
        self.assertIn(".turn-modal-body.cleanup-confirm-body {\n      height: 156px;\n      min-height: 156px;\n      padding-bottom: 16px;", source)
        self.assertIn(".cleanup-confirm-progress {\n      display: grid;", source)
        self.assertIn(".cleanup-confirm-progress-fill {\n      height: 100%;", source)
        self.assertIn(".cleanup-control-row {\n      display: flex;", source)
        self.assertIn(".cleanup-retention-form .cleanup-option {\n      margin-left: 12px;", source)
        self.assertIn(".cleanup-action-row {\n      display: grid;", source)
        self.assertIn("--cleanup-refresh-button-width: 92px;", source)
        self.assertIn("grid-template-columns: minmax(180px, 1fr) var(--cleanup-refresh-button-width) 120px;", source)
        self.assertIn(".cleanup-action-row button {\n      width: 100%;\n      min-width: 0;", source)
        self.assertIn("button.disabled = !state.cleanupRetentionAvailable;", source)
        self.assertNotIn("button.disabled = allMode ? serviceBytes <= 0 : selectedRows <= 0;", source)
        self.assertIn("margin-left: auto;", source)
        self.assertLess(source.index('id="cleanup-action-status"'), source.index('id="cleanup-refresh"'))
        self.assertIn("grid-template-columns: minmax(0, 1fr);", source)
        self.assertIn("grid-template-rows: minmax(250px, 1fr) auto;", source)
        self.assertIn("grid-template-rows: minmax(180px, 1fr) auto;", source)
        self.assertIn("#cleanup-files tbody {\n        align-content: start;\n        grid-template-rows: repeat(var(--cleanup-row-count), minmax(0, 42px));", source)
        self.assertNotIn(".cleanup-detail-panel {\n      grid-column: 2;\n      grid-row: 1 / -1;", source)
        self.assertIn(".cleanup-files-panel {\n      grid-column: 1;", source)
        self.assertIn("grid-row: 2;\n      min-height: 523px;", source)
        self.assertIn(".cleanup-workbench-panel,\n    .cleanup-side {\n      min-height: 0;", source)
        self.assertNotIn(".cleanup-workbench-panel,\n    .cleanup-files-panel,\n    .cleanup-side {\n      min-height: 0;", source)
        self.assertIn("Segment Rows", source)
        self.assertNotIn("Affected Rows", source)
        self.assertNotIn('<div class="label" id="cleanup-selected-label">Rows To Delete</div>', source)
        self.assertNotIn("Bytes To Delete", source)
        self.assertIn("Delete Before", source)
        self.assertIn("Affected Files", source)
        self.assertIn('class="cleanup-retention-main"', source)
        self.assertIn('class="cleanup-retention-split"', source)
        self.assertIn('class="cleanup-retention-stat"', source)
        self.assertIn(".cleanup-retention-form", source)
        self.assertIn(".cleanup-action-body {\n      display: flex;\n      flex: 1 1 auto;\n      min-height: 0;\n      flex-direction: column;", source)
        self.assertIn(".cleanup-selection-summary {\n      display: grid;\n      grid-template-columns: minmax(250px, 1.05fr) minmax(0, 1.35fr);", source)
        self.assertIn(".cleanup-retention-main {\n      display: grid;", source)
        self.assertIn("align-content: center;\n      gap: clamp(8px, 1.25vh, 12px);", source)
        self.assertIn(".cleanup-retention-split {\n      display: grid;", source)
        self.assertIn("grid-template-rows: repeat(2, minmax(0, 1fr));", source)
        self.assertIn(".cleanup-retention-stat {\n      display: grid;", source)
        self.assertIn("grid-template-columns: minmax(108px, 0.45fr) minmax(0, 1fr);", source)
        self.assertIn(".cleanup-retention-form .cleanup-action-row button,\n    .cleanup-retention-custom input[type=\"date\"] {\n      height: 36px;", source)
        self.assertIn("@media (max-height: 820px) {\n      .cleanup-layout {\n        gap: 10px;", source)
        self.assertIn(".cleanup-files-panel {\n        min-height: 471px;\n      }", source)
        self.assertIn("min-height: 56px;\n        gap: 6px;\n        padding: 8px 12px;", source)
        self.assertIn("border-top: 1px solid var(--border);", source)
        self.assertIn(".cleanup-retention-presets", source)
        self.assertIn("min-width: 64px;\n      border: 1px solid var(--border);", source)
        self.assertIn("white-space: nowrap;\n      cursor: pointer;", source)
        self.assertIn("font-size: clamp(22px, 3.2vh, 28px);", source)
        self.assertIn(".cleanup-retention-presets button {\n        min-width: 46px;\n        padding-left: 6px;", source)
        self.assertIn("function cleanupRetentionDate()", source)
        self.assertIn("function setCleanupRetentionMode(value)", source)
        self.assertIn("[1, 7, 14, 30, 90]", source)
        self.assertIn("['1', '7', '14', '30', '90', 'all', 'custom']", source)
        self.assertIn("function cleanupAllMode()", source)
        self.assertIn("function allModeRetentionRows(retention)", source)
        self.assertIn("function cleanupRetentionFilesForMode()", source)
        self.assertIn("mode === 'all'", source)
        self.assertIn("if (input && mode === 'all') input.value = '';", source)
        self.assertNotIn("input.disabled = mode === 'all'", source)
        self.assertIn("function cleanupRawSegmentRows(rows = state.cleanupRows || [])", source)
        self.assertIn("const rawSegmentRows = cleanupRawSegmentRows();", source)
        self.assertIn("function cleanupHasRetentionWork(retention = ((state.cleanupRetention || {}).selected || {}))", source)
        self.assertIn("const pendingTurnStateFiles = Number((retention || {}).pending_turn_state_deletable_files || 0);", source)
        self.assertIn("return selectedRows > 0 || pendingTurnStateFiles > 0;", source)
        self.assertIn("if (selectedLabelEl) selectedLabelEl.textContent = 'Segment Rows';", source)
        self.assertIn("selectedBytesEl.textContent = cleanupCountLabel(rawSegmentRows, 'row');", source)
        self.assertIn("affectedFilesEl.textContent = cleanupCountLabel(totals.affectedFiles, 'file');", source)
        self.assertNotIn("function cleanupSelectedSourceFileCount()", source)
        self.assertNotIn("const selectedRows = allMode ? allModeRetentionRows(retention) : Number(retention.deletable_rows || 0);", source)
        self.assertNotIn("selectedLabelEl.textContent = allMode ? 'Bytes To Delete' : 'Rows To Delete';", source)
        self.assertIn("cleanupRetentionMode: state.cleanupRetentionMode,", source)
        self.assertIn("cleanupRetentionDate: document.getElementById('cleanup-retention-date').value,", source)
        self.assertIn("const cleanupMode = normalizeCleanupRetentionMode(settings.cleanupRetentionMode);", source)
        self.assertIn("if (typeof settings.cleanupRetentionDate === 'string' && /^\\d{4}-\\d{2}-\\d{2}$/.test(settings.cleanupRetentionDate)) {", source)
        self.assertIn("document.getElementById('cleanup-retention-date').value = settings.cleanupRetentionDate;", source)
        self.assertIn("setCleanupRetentionMode(cleanupMode);", source)
        self.assertIn("setCleanupRetentionMode(button.dataset.cleanupRetentionPreset);\n    saveSettings();", source)
        self.assertIn("setCleanupRetentionMode('custom');\n  saveSettings();", source)
        self.assertIn("if (cleanupAllMode()) {", source)
        self.assertNotIn("function cleanupImpactForRow(row)", source)
        self.assertIn("function cleanupImpactTotals(rows = state.cleanupRows || [])", source)
        self.assertIn("function cleanupRawSegmentRows(rows = state.cleanupRows || [])", source)
        self.assertNotIn("function cleanupSelectedSourceFileCount()", source)
        self.assertNotIn("function cleanupImpactTotals(key)", source)
        self.assertIn("function retentionStatsForRow(row)", source)
        self.assertIn("deletableBytes: Number(display.delete_size || 0),", source)
        self.assertIn("const affectedFiles = Number(display.affected_files || 0);", source)
        self.assertNotIn("targetFiles", source)
        self.assertIn("function cleanupRetentionEffect(row)", source)
        self.assertIn("row.retention_effect", source)
        self.assertIn("function renderCleanupTable(rows)", source)
        self.assertIn("function updateCleanupFileRows()", source)
        self.assertIn("function cleanupRowsSignature(rows)", source)
        self.assertIn("row.group_id || '',\n    row.retention_effect || '',", source)
        self.assertIn("{label:'Total Size', cls:'num'}", source)
        self.assertIn("{label:'Affected Size', cls:'num'}", source)
        self.assertNotIn("{label:'Total Files', cls:'num cleanup-total-files-header'}", source)
        self.assertNotIn("{label:'', cls:'cleanup-affected-files-spacer', ariaHidden:true}", source)
        self.assertIn("{label:'Affected Files', cls:'cleanup-affected-files-header'}", source)
        self.assertIn("cleanupDisplayForRow,", source)
        self.assertIn("function cleanupActionFileCounts(row, stats = retentionStatsForRow(row))", source)
        self.assertNotIn("function cleanupActionMixItems(", source)
        self.assertNotIn("const CLEANUP_ACTION_ORDER", source)
        self.assertNotIn("cleanupActionColumnDemoCounts", source)
        self.assertIn("function cleanupActionFileColumnText(count)", source)
        self.assertIn("function cleanupFileColumnNumberText(count)", source)
        self.assertNotIn("function cleanupTotalFilesColumnText(count)", source)
        self.assertNotIn("function cleanupTotalFilesCount(row, stats = retentionStatsForRow(row))", source)
        self.assertNotIn("cleanupTotalFilesDemoCount", source)
        self.assertIn("function cleanupAffectedFilesTotalCount(row, stats = retentionStatsForRow(row))", source)
        self.assertIn("function cleanupAffectedFilesSummaryItems(row, stats = retentionStatsForRow(row))", source)
        self.assertIn("function cleanupAffectedFilesSummaryLabel(label)", source)
        self.assertIn("function cleanupAffectedFilesSummaryTitle(row, stats = retentionStatsForRow(row))", source)
        self.assertIn("function cleanupAffectedFilesSummaryIcon(label)", source)
        self.assertIn("function renderCleanupAffectedFilesSummaryCell(row, stats = retentionStatsForRow(row))", source)
        self.assertNotIn("const countedFiles = [...counts.values()].reduce((total, count) => total + count, 0);", source)
        self.assertNotIn("counts.set(operation, affectedFiles);", source)
        self.assertIn("return cleanupFileColumnNumberText(normalized);", source)
        self.assertIn("function cleanupFileColumnNumberText(count) {\n  const normalized = Math.max(0, Number(count || 0));\n  return compactNumber(normalized);\n}", source)
        self.assertNotIn("function cleanupFileColumnNumberText(count) {\n  const normalized = Math.max(0, Number(count || 0));\n  return fmt.format(normalized);\n}", source)
        self.assertNotIn("return normalized > 0 ? cleanupFileColumnNumberText(normalized) : '-';", source)
        self.assertNotIn(": [summary.operation || '-'];", source)
        self.assertIn('class="cleanup-affected-files-summary"', source)
        self.assertIn('aria-label="${esc(title)}"', source)
        self.assertIn('class="cleanup-affected-files-part"', source)
        self.assertIn('class="cleanup-affected-files-icon"', source)
        self.assertIn('class="cleanup-affected-files-value"', source)
        self.assertIn(".cleanup-affected-files-value {\n      display: inline-block;\n      width: 5ch;\n      min-width: 5ch;\n      text-align: left;", source)
        self.assertIn('const iconLabel = cleanupAffectedFilesSummaryLabel(label);', source)
        self.assertIn('title="${esc(iconLabel)}"', source)
        self.assertIn('aria-label="${esc(iconLabel)}"', source)
        self.assertIn("cleanupAffectedFilesSummaryIcon(label)", source)
        self.assertNotIn('class="cleanup-affected-files-context"', source)
        self.assertNotIn("function cleanupActionMixContext(items)", source)
        self.assertIn("cleanupAffectedFilesSummaryTitle(row, stats)", source)
        self.assertIn("renderCleanupAffectedFilesSummaryCell(row, stats)", source)
        self.assertIn("const summary = cleanupSummaryForRow(row);", source)
        self.assertIn("const stats = retentionStatsForRow(row);", source)
        self.assertIn("const sizeCell = rowEl.querySelector('.cleanup-size-cell');", source)
        self.assertIn("const affectedSizeCell = rowEl.querySelector('.cleanup-affected-size-cell');", source)
        self.assertNotIn("const totalFilesCell = rowEl.querySelector('.cleanup-total-files-cell');", source)
        self.assertNotIn("const totalFilesValue = rowEl.querySelector('.cleanup-total-files-value');", source)
        self.assertIn("const affectedFilesCell = rowEl.querySelector('.cleanup-affected-files-cell');", source)
        self.assertNotIn("cleanupTotalFilesColumnText(cleanupTotalFilesCount(row, stats))", source)
        self.assertNotIn("cleanup-scope-cell", source)
        self.assertNotIn("cleanup-scanned-rows-cell", source)
        self.assertNotIn("cleanup-delete-rows-cell", source)
        self.assertIn("preserveRows: true", source)
        self.assertIn("function renderCleanupFileDetail(row, detailRow = row)", source)
        self.assertIn("function openCleanupDetailModal(rowEl)", source)
        self.assertIn("function closeCleanupDetailModal()", source)
        self.assertIn('aria-label="${esc(cleanupFileGroupDisplay(row.label || \'\'))}. Press Enter or Space to open file detail."', source)
        self.assertIn('aria-haspopup="dialog"', source)
        self.assertIn("row.addEventListener('dblclick'", source)
        self.assertIn("if (event.key === 'Enter' || event.key === ' ')", source)
        self.assertNotIn('<tr tabindex="0" role="button" aria-selected="false" data-cleanup-index="${index}" data-cleanup-file=', source)
        self.assertIn("function selectCleanupFileRow(row)", source)
        self.assertNotIn("function cleanupStatusLabel(value)", source)
        self.assertIn("const retention = (state.cleanupRetention || {}).selected || {};", source)
        self.assertIn("async function loadCleanup(options = {})", source)
        self.assertIn("cleanupSeq: 0", source)
        self.assertIn("const seq = ++state.cleanupSeq;", source)
        self.assertIn("if (seq !== state.cleanupSeq) return;", source)
        self.assertIn("await getJSON('/api/log-cleanup?' + q)", source)
        self.assertIn("preview_signature: previewSignature", source)
        self.assertIn("await postJSON('/api/log-cleanup/retention', {cutoff_date: cutoffDate, preview_signature: previewSignature})", source)
        self.assertIn("Object.assign(error, data);", source)
        self.assertIn("Delete changed data but rebuild failed", source)
        self.assertIn("document.querySelectorAll('[data-cleanup-retention-preset]')", source)
        self.assertIn("This deletes every eligible raw log row across service-managed files", source)
        self.assertIn("This deletes every raw log row across service-managed files", source)
        self.assertIn("min-width: 0;", source)
        self.assertIn("['deletable', 'protected', 'clean', 'missing']", source)
        self.assertNotIn(">Actions<", source)
        self.assertIn("Total Size", source)
        self.assertIn("Affected Size", source)
        self.assertIn("Total Files", source)
        self.assertNotIn("Total Rows", source)
        self.assertNotIn("Affected Rows", source)
        self.assertIn("Affected Files", source)
        self.assertNotIn("Delete Size", source)
        self.assertIn("{label:'Total Size', cls:'num'}", source)
        self.assertIn("{label:'Affected Size', cls:'num'}", source)
        self.assertNotIn("{label:'Total Files', cls:'num cleanup-total-files-header'}", source)
        self.assertIn("{label:'Affected Files', cls:'cleanup-affected-files-header'}", source)
        self.assertNotIn("function cleanupActionLabel(row, stats)", source)
        self.assertNotIn("Delete Old Logs", source)
        self.assertIn("#cleanup-files tr[data-cleanup-file] {\n      cursor: default;", source)
        self.assertIn("#cleanup-files tr[data-cleanup-file].selected:hover td {\n      background: var(--row-selected);", source)
        self.assertIn("#cleanup-files tr[data-cleanup-file]:focus-visible td:first-child {\n      box-shadow: inset 3px 0 0 var(--accent-2);", source)
        self.assertIn("row.classList.toggle('selected', active);", source)
        self.assertIn("row.setAttribute('aria-selected', active ? 'true' : 'false');", source)
        self.assertNotIn("Source Type", source)
        self.assertIn("data-cleanup-file=", source)
        self.assertIn("<col class=\"cleanup-file-col\">", source)
        self.assertIn("#cleanup-files table {\n      display: grid;\n      grid-template-rows: auto minmax(0, 1fr);\n      table-layout: fixed;", source)
        self.assertIn("#cleanup-files tbody {\n      grid-template-rows: repeat(var(--cleanup-row-count), minmax(0, 1fr));", source)
        self.assertIn("<tbody style=\"--cleanup-row-count:${rowCount}\">", source)
        self.assertIn("return renderCleanupTableFrame(body, rows.length);", source)
        self.assertIn("--cleanup-file-columns: minmax(0, 36fr) minmax(0, 15fr) minmax(0, 15fr) minmax(0, 34fr);", source)
        self.assertIn("#cleanup-files .cleanup-file-col { width: 36%; }", source)
        self.assertIn("#cleanup-files .cleanup-size-col { width: 15%; }", source)
        self.assertIn("#cleanup-files .cleanup-affected-size-col { width: 15%; }", source)
        self.assertNotIn("#cleanup-files .cleanup-total-files-col", source)
        self.assertNotIn("#cleanup-files .cleanup-affected-files-spacer-col", source)
        self.assertIn("#cleanup-files .cleanup-affected-files-col { width: 34%; }", source)
        self.assertNotIn("18px minmax(0, 30fr)", source)
        self.assertNotIn("72px minmax", source)
        self.assertNotIn('class="cleanup-total-files-value"', source)
        self.assertNotIn(".cleanup-total-files-value {", source)
        self.assertNotIn("#cleanup-files th.cleanup-affected-files-header,\n    .cleanup-affected-files-cell {\n      padding-left:", source)
        self.assertIn("#cleanup-files th.cleanup-affected-files-header {\n      justify-content: center;\n      text-align: center;", source)
        self.assertIn("#cleanup-files th.num,\n    #cleanup-files td.num {\n      justify-content: flex-end;\n      text-align: right;", source)
        self.assertNotIn("cleanup-total-files-spacer", source)
        self.assertNotIn("cleanup-affected-files-spacer", source)
        self.assertNotIn("cleanup-column-spacer", source)
        self.assertNotIn("<td class=\"cleanup-affected-files-spacer\" aria-hidden=\"true\"></td>", source)
        self.assertNotIn("#cleanup-files th.cleanup-total-files-header,\n    .cleanup-total-files-cell {\n      padding-right: 72px;", source)
        self.assertNotIn("#cleanup-files th.cleanup-total-files-header,\n    .cleanup-total-files-cell {\n      padding-right: 36px;", source)
        self.assertNotIn("#cleanup-files th.cleanup-total-files-header,\n    .cleanup-total-files-cell {\n      padding-right: 28px;", source)
        self.assertNotIn("#cleanup-files th.cleanup-total-files-header,\n    .cleanup-total-files-cell {\n      padding-right: 32px;", source)
        self.assertIn(".cleanup-affected-files-cell {\n      justify-content: center;\n      min-width: 0;\n      line-height: 16px;\n      text-align: center;", source)
        self.assertNotIn(".cleanup-affected-files-cell {\n      justify-content: center;\n      min-width: 0;\n      padding-right: 18px;\n      padding-left: 18px;", source)
        self.assertIn("<col class=\"cleanup-size-col\">", source)
        self.assertIn("<col class=\"cleanup-affected-size-col\">", source)
        self.assertNotIn("<col class=\"cleanup-total-files-col\">", source)
        self.assertNotIn("<col class=\"cleanup-affected-files-spacer-col\">", source)
        self.assertIn("<col class=\"cleanup-affected-files-col\">", source)
        self.assertNotIn("<col class=\"cleanup-delete-files-col\">", source)
        self.assertNotIn("<col class=\"cleanup-rebuild-files-col\">", source)
        self.assertNotIn("<col class=\"cleanup-rewrite-files-col\">", source)
        self.assertNotIn("<col class=\"cleanup-operation-col\">", source)
        self.assertNotIn("<col class=\"cleanup-delete-size-col\">", source)
        self.assertNotIn("<col class=\"cleanup-affected-rows-col\">", source)
        self.assertNotIn("<col class=\"cleanup-scope-col\">", source)
        self.assertNotIn("<col class=\"cleanup-scanned-rows-col\">", source)
        self.assertNotIn("<col class=\"cleanup-old-ratio-col\">", source)
        self.assertNotIn("<col class=\"cleanup-action-col\">", source)
        self.assertIn("summary.deleteSize", source)
        self.assertNotIn("cleanupPercent(stats.oldRatio)", source)
        self.assertNotIn("<col class=\"cleanup-status-col\">", source)
        self.assertIn("#cleanup-files th,\n    #cleanup-files td {\n      padding-top: 8px;\n      padding-bottom: 8px;", source)
        self.assertIn("#cleanup-files {\n      --cleanup-file-columns:", source)
        self.assertIn("display: flex;\n      flex: 1 1 auto;\n      min-height: 0;\n      overflow: hidden;\n      padding-bottom: 0;", source)
        self.assertIn("#cleanup-files .table-scroll {\n      display: flex;\n      flex: 1 1 auto;\n      min-height: 0;\n      overflow-x: auto;\n      overflow-y: hidden;", source)
        self.assertIn("@media (max-height: 820px) {\n      .cleanup-layout {\n        gap: 10px;", source)
        self.assertIn("@media (max-height: 740px) {", source)
        self.assertIn(".cleanup-files-panel {\n        min-height: 412px;\n      }", source)
        self.assertIn("@media (max-height: 740px) {\n      .cleanup-layout {\n        grid-template-rows: minmax(160px, 1fr) minmax(0, 1fr);", source)
        self.assertIn(".cleanup-files-panel {\n        min-height: 0;\n      }", source)
        self.assertIn("return row ? Number(retentionStatsForRow(row).deletableRows || 0) : 0;", source)
        self.assertNotIn(".cleanup-status.clean", source)
        self.assertNotIn(".cleanup-summary-grid", source)
        self.assertNotIn("Archive Applied Raw Logs", source)
        self.assertNotIn("Minimum applied size", source)

    def test_cleanup_initial_loading_uses_table_skeleton_to_prevent_layout_shift(self) -> None:
        source = dashboard_asset_bundle()

        self.assertIn('id="cleanup-files" class="loading"><div class="table-scroll">', source)
        self.assertIn("function renderCleanupTableLoading(message = 'Loading cleanup data.')", source)
        self.assertIn("function renderCleanupAffectedFilesSummaryLoadingCell()", source)
        self.assertIn("function setCleanupActionLoading()", source)
        self.assertIn("setCleanupActionLoading();", source)
        self.assertIn("cleanup-summary-loading-cell", source)
        self.assertIn("setPanelContent('cleanup-files', renderCleanupTableLoading(), 'loading');", source)
        self.assertIn("#cleanup-files.loading {\n      padding: 0;", source)
        self.assertIn("min-width: 860px;\n      width: 100%;", source)
        self.assertIn("cleanup-loading-row", source)
        self.assertIn('return `<span class="sr-only">${esc(message)}</span>${renderCleanupTableFrame(body, rowCount, {ariaBusy: true, ariaLabel: message})}`;', source)
        self.assertIn("const busyAttr = options.ariaBusy ? ' aria-busy=\"true\"' : '';", source)
        self.assertIn("const labelAttr = options.ariaLabel ? ` aria-label=\"${esc(options.ariaLabel)}\"` : '';", source)
        self.assertIn('aria-busy="true" aria-label="Loading cleanup data."', source)
        self.assertIn('class="truncate-cell cleanup-file-cell"', source)
        self.assertIn('class="num cleanup-size-cell"', source)
        self.assertIn('class="num cleanup-affected-size-cell"', source)
        self.assertIn('class="cleanup-affected-files-cell"', source)
        self.assertIn("cleanup-affected-files-loading", source)
        self.assertIn("data-kind=\"${esc(kind)}\"", source)
        self.assertNotIn('id="cleanup-selected-count">cutoff loading</div>', source)
        self.assertNotIn("selectedBytesEl.textContent = 'loading';", source)
        self.assertNotIn("selectedCountEl.textContent = 'cutoff loading';", source)
        self.assertNotIn("affectedFilesEl.textContent = 'loading';", source)
        self.assertNotIn("setPanelContent('cleanup-files', 'Loading cleanup data.', 'loading');", source)

    def test_cleanup_response_updates_summary_and_impact_in_one_commit(self) -> None:
        source = dashboard_asset_bundle()

        self.assertIn("function commitCleanupView(", source)
        self.assertIn("commitCleanupView({summary, rows, previousSignature, nextSignature, tableExists, options});", source)
        self.assertLess(
            source.index("updateCleanupActionState(summary);"),
            source.index("setPanelContent('cleanup-files', renderCleanupTable(rows));"),
        )

    def test_subagent_confidence_includes_retention_pruned_parent(self) -> None:
        queries = load_module("dashboard_queries_retention_confidence_test", ROOT / "scripts" / "dashboard_queries.py")
        source = dashboard_asset_bundle()

        self.assertIn("parent_pruned_by_retention", queries.SUBAGENT_CONFIDENCE_ORDER)
        self.assertIn("parent pruned", source)
        self.assertIn("parent turn was removed by retention while the child session remains visible", source)

    def test_log_cleanup_ui_exposes_all_retention_preset_delete_action(self) -> None:
        source = dashboard_asset_bundle()

        self.assertNotIn('id="cleanup-delete-all"', source)
        self.assertNotIn(">Delete All</button>", source)
        self.assertIn('data-cleanup-retention-preset="all"', source)
        self.assertIn("deleteAllLogs()", source)
        self.assertIn("if (cleanupAllMode()) {\n    await deleteAllLogs();\n    return;\n  }", source)
        self.assertIn("'/api/log-cleanup/all'", source)

    def test_cleanup_file_detail_replaces_summary_panel(self) -> None:
        source = dashboard_asset_bundle()
        self.assertNotIn(".cleanup-detail-panel,\n    .cleanup-files-panel {\n      display: flex;\n      flex-direction: column;", source)
        self.assertIn(".cleanup-files-panel {\n      grid-column: 1;\n      grid-row: 2;", source)
        self.assertNotIn(".cleanup-detail-panel {\n      grid-column: 2;\n      grid-row: 1 / -1;", source)
        self.assertIn(".cleanup-detail {\n      display: grid;", source)
        self.assertIn("grid-template-rows: auto minmax(0, 1fr) auto;", source)
        self.assertIn("height: 100%;", source)
        self.assertIn(".cleanup-detail.loading {\n      padding: 0;", source)
        self.assertIn(".cleanup-modal-body {\n      flex: 1 1 auto;", source)
        self.assertIn(".turn-modal-dialog.cleanup-modal-dialog {\n      width: 1040px;\n      height: 720px;", source)
        self.assertIn("id=\"cleanup-detail-modal\"", source)
        self.assertIn("id=\"cleanup-detail-modal-body\"", source)
        self.assertIn(".cleanup-detail-hero {\n      display: grid;", source)
        self.assertIn("grid-template-columns: minmax(0, 1fr) minmax(360px, 400px);", source)
        self.assertNotIn("grid-template-columns: minmax(0, 88px) minmax(0, 176px);", source)
        self.assertIn(".cleanup-detail-identity {\n      display: grid;\n      gap: 10px;", source)
        self.assertIn(".cleanup-detail-heading {\n      min-width: 0;", source)
        self.assertNotIn(".cleanup-detail-group {", source)
        self.assertIn(".cleanup-detail-description-name {", source)
        self.assertIn(".cleanup-detail-description-copy {", source)
        self.assertIn(".cleanup-detail-meta {", source)
        self.assertIn(".cleanup-detail-meta-value {", source)
        self.assertIn(".cleanup-detail-summary {\n      display: grid;", source)
        self.assertIn("grid-template-columns: repeat(4, minmax(0, 1fr));", source)
        self.assertIn("column-gap: 12px;", source)
        self.assertIn("width: min(100%, 320px);", source)
        self.assertIn("justify-self: end;", source)
        self.assertIn(".cleanup-detail-summary-icon {", source)
        self.assertIn("justify-content: center;", source)
        self.assertIn(".cleanup-detail-summary-icon svg {", source)
        self.assertIn(".cleanup-detail-summary dd {\n      min-width: 0;\n      margin: 0;\n      color: var(--text);\n      font-family: var(--mono);\n      font-size: 16px;", source)
        self.assertIn("line-height: 20px;", source)
        self.assertIn(':root[data-theme="dark"] .cleanup-detail-summary dt,', source)
        self.assertIn(':root[data-theme="dark"] .cleanup-affected-file-directory-label,', source)
        self.assertIn(':root[data-theme="dark"] .cleanup-affected-file-path {', source)
        self.assertIn("color: var(--muted);", source)
        self.assertNotIn(".cleanup-detail-context", source)
        self.assertNotIn(".cleanup-detail-facts", source)
        self.assertIn(".cleanup-affected-file-ledger {\n      display: grid;\n      grid-template-rows: auto minmax(0, 1fr);", source)
        self.assertNotIn(".cleanup-affected-file-section", source)
        self.assertNotIn(".cleanup-affected-file-list-head", source)
        self.assertNotIn(".cleanup-affected-file-columns {", source)
        self.assertIn(".cleanup-affected-file-row {\n      height: 85px;", source)
        self.assertIn("max-height: 85px;", source)
        self.assertIn(".cleanup-affected-file-loading-row {\n      height: 85px;", source)
        self.assertIn("padding: 12px 24px;", source)
        self.assertIn("position: relative;", source)
        self.assertIn(".cleanup-affected-file-cell {\n      display: flex;", source)
        self.assertIn(".cleanup-affected-file-name {\n      min-width: 0;", source)
        self.assertIn(".cleanup-affected-file-path {\n      display: -webkit-box;", source)
        self.assertIn("flex: 1 1 auto;", source)
        self.assertIn("min-width: 0;", source)
        self.assertIn("white-space: normal;", source)
        self.assertIn("-webkit-line-clamp: 2;", source)
        self.assertIn(".cleanup-affected-file-list > .cleanup-affected-file-row:last-child {\n      border-bottom: 0;", source)
        self.assertIn(".cleanup-affected-file-action {", source)
        self.assertIn("width: 72px;", source)
        self.assertIn("top: 50%;", source)
        self.assertIn("right: 24px;", source)
        self.assertIn("transform: translateY(-50%);", source)
        self.assertIn(".cleanup-affected-file-directory {\n      display: flex;", source)
        self.assertIn(".cleanup-affected-file-row-main {\n      display: grid;", source)
        self.assertIn("grid-template-columns: minmax(0, 1fr) 72px;", source)
        self.assertIn("gap: 28px;", source)
        self.assertIn(':root[data-theme="dark"] .cleanup-affected-file-action[data-action="rebuild"],', source)
        self.assertIn(':root[data-theme="dark"] .cleanup-affected-file-action[data-action="rewrite"] {', source)
        self.assertIn("color-mix(in srgb, #f1f1f1 48%, var(--muted));", source)
        self.assertIn(':root[data-theme="dark"] .cleanup-affected-file-action[data-action="delete"] {', source)
        self.assertIn(".cleanup-affected-file-action-icon {", source)
        self.assertIn(".cleanup-affected-file-action-icon svg {", source)
        self.assertIn("stroke-width: 1.45;", source)
        self.assertIn("background: transparent;", source)
        self.assertIn("border: 0;", source)

    def test_cleanup_ui_clears_stale_status_and_wraps_mobile_modal(self) -> None:
        source = dashboard_asset_bundle()
        self.assertIn("error.status = res.status;", source)
        self.assertIn("error.code = parsed.error || '';", source)
        self.assertIn("function isServiceBusyError(err)", source)
        self.assertIn("function clearCleanupStatus()", source)
        self.assertIn("if (!options.keepStatus) clearCleanupStatus();", source)
        self.assertIn(".cleanup-detail-hero {\n        grid-template-columns: 1fr;", source)
        self.assertIn(".cleanup-modal-body {\n        overflow: auto;", source)
        self.assertNotIn(".cleanup-affected-file-number {", source)
        self.assertNotIn("cleanup-affected-file-number-unit", source)
        self.assertIn("text-overflow: ellipsis;", source)
        self.assertNotIn(".cleanup-affected-file-facts", source)
        self.assertNotIn(".cleanup-affected-file-fact", source)
        self.assertNotIn(".cleanup-affected-file-subline", source)
        self.assertNotIn(".cleanup-affected-file-progress", source)
        self.assertIn(".cleanup-affected-file-header {\n      display: flex;", source)
        self.assertNotIn(".cleanup-affected-file-stats", source)
        self.assertNotIn(".cleanup-affected-file-stat:first-child", source)
        self.assertNotIn(".cleanup-file-identity::before", source)
        self.assertNotIn(".cleanup-file-detail.deletable .cleanup-file-identity::before", source)
        self.assertNotIn('class="cleanup-detail tool-detail-summary', source)
        self.assertNotIn('class="cleanup-detail tool-name-cell', source)
        self.assertNotIn(".cleanup-file-detail .tool-detail-grid", source)
        self.assertIn("function cleanupFileGroupDescription(label)", source)
        self.assertIn("'Raw Current Segments': 'active raw segments'", source)
        self.assertIn("'Normalized Outputs': 'normalized raw-log outputs'", source)
        self.assertIn("'Analytics Database': 'analytics SQLite database'", source)
        self.assertIn("'Archived Raw Logs': 'archived raw prefixes'", source)
        self.assertIn("'Pending Turn State': 'orphan turn-start state'", source)
        self.assertIn("'State Files': 'processing state indexes'", source)
        self.assertNotIn("'Temporary Files': 'transient analysis files'", source)
        self.assertNotIn("'Parse Error Logs': 'rejected JSONL rows'", source)
        self.assertNotIn("'Raw Current Segments': 'current pointer raw segments selected for rotation'", source)
        self.assertNotIn("'Normalized Outputs': 'normalized prompt outputs generated from raw logs'", source)
        self.assertNotIn("'Analytics Database': 'SQLite dashboard database built from normalized data'", source)
        self.assertNotIn("'Archived Raw Logs': 'raw log prefixes already moved out of active files'", source)
        self.assertNotIn("'Pending Turn State': 'orphan turn-start recovery files waiting for Stop or reconcile'", source)
        self.assertNotIn("'State Files': 'incremental processing state and retention indexes'", source)
        self.assertNotIn("'Temporary Files': 'transient analysis work files owned by this service'", source)
        self.assertNotIn("'Parse Error Logs': 'rejected JSONL rows retained for troubleshooting'", source)
        self.assertIn("function cleanupFileGroupDisplay(label)", source)
        self.assertNotIn("'Raw Usage Logs': 'Raw Usage Logs'", source)
        self.assertIn("'Raw Current Segments': 'Current Raw Segments'", source)
        self.assertNotIn("'Reports': 'Generated Reports'", source)
        self.assertNotIn("function cleanupDisplayFileName(path)", source)
        self.assertIn("function cleanupDetailFilesForRow(row)", source)
        self.assertIn("function cleanupDetailLedgerFilesForRow(row)", source)
        self.assertIn("if (cleanupAllMode()) return files;", source)
        self.assertNotIn("function cleanupDeletionTargetFilesForRow(row)", source)
        self.assertNotIn("const impact = cleanupImpactForRow(row);", source)
        self.assertIn("return cleanupSummaryForRow(row).targets.map(path => ({", source)
        self.assertNotIn("function cleanupFileModifiedLabel(file)", source)
        self.assertIn("function cleanupRetentionState(row, stats)", source)
        self.assertNotIn("function cleanupRetentionRole(row)", source)
        self.assertNotIn("function cleanupRowHasCapability(row, capability)", source)
        self.assertNotIn("function cleanupUsesDirectDeleteImpact(row)", source)
        self.assertNotIn("return cleanupRowHasCapability(row, 'direct_delete');", source)
        self.assertIn("function cleanupSummaryForRow(row)", source)
        self.assertIn("hasTargets: Array.isArray(display.targets)", source)
        self.assertIn("hasItems: Array.isArray(display.items)", source)
        self.assertNotIn("cleanupAllMode() || cleanupUsesDirectDeleteImpact(row) ? 'delete_all_impact' : 'retention_impact'", source)
        self.assertIn("cleanupAllMode() ? 'delete_all_display' : 'display'", source)
        self.assertNotIn("'Raw Usage Logs': 'active raw prompt logs captured by the service'", source)
        self.assertIn("'Raw Current Segments': 'active raw segments'", source)
        self.assertIn("function cleanupCutoffLabel()", source)
        self.assertIn("const summary = cleanupSummaryForRow(row);", source)
        self.assertNotIn("function cleanupDetailModalSubtitle(row, stats)", source)
        self.assertNotIn("return cleanupFileGroupDisplay((row || {}).label || '');", source)
        self.assertNotIn("const noun = 'affected file';", source)
        self.assertNotIn("detailFileLabel", source)
        self.assertIn("function cleanupImpactTotals(rows = state.cleanupRows || [])", source)
        self.assertIn("for (const row of rows || []) {", source)
        self.assertIn("totals.affectedFiles += Number(stats.affectedFiles || 0);", source)
        self.assertIn("return totals;", source)
        self.assertNotIn("function cleanupImpactTotals(key)", source)
        self.assertNotIn("cleanupDetailModalSubtitle(selected, stats)", source)
        self.assertIn("loadCleanupDetail(selected);", source)
        self.assertIn("q.set('group_id', cleanupRowId(row));", source)
        self.assertIn("getJSON('/api/log-cleanup/detail?' + q)", source)
        self.assertNotIn("q.set('label'", source)
        self.assertNotIn("${compactNumber(stats.affectedFiles || 0)} target files", source)
        self.assertNotIn("Target Files", source)
        self.assertIn("const paths = summary.hasTargets ? summary.targets : cleanupRowPaths(row);", source)
        self.assertIn("if (summary.hasTargets) return cleanupFilesFromPaths(summary.targets, row);", source)
        self.assertNotIn("if (summary.targets.length) return cleanupFilesFromPaths(summary.targets, row);", source)
        self.assertIn("is_derived_output: Boolean(options.isDerivedOutput),", source)
        self.assertIn("function renderCleanupDetailSummary(row, stats)", source)
        self.assertIn("function cleanupHasAffectedFileImpact(row, stats = retentionStatsForRow(row))", source)
        self.assertIn("if (!cleanupHasAffectedFileImpact(row, stats)) return [];", source)
        self.assertNotIn("function cleanupHasRowImpact(row)", source)
        self.assertNotIn("function cleanupAffectedRowsValue", source)
        self.assertNotIn("function cleanupAffectedRowsTitle", source)
        self.assertNotIn("cleanupDefinitionItem('Affected Rows'", source)
        self.assertIn("function cleanupDetailSummaryItems(row, stats)", source)
        self.assertIn("function cleanupDetailCutoffMeta()", source)
        self.assertIn('<div class="cleanup-detail-meta"><span>Delete before</span><span class="cleanup-detail-meta-value">${esc(cleanupCutoffDateLabel())}</span></div>', source)
        self.assertIn("return cleanupAffectedFilesSummaryItems(row, stats);", source)
        self.assertIn('<div class="cleanup-detail-heading">', source)
        self.assertIn("const groupDisplay = cleanupFileGroupDisplay(groupName);", source)
        self.assertIn("const description = `${cleanupFileGroupDescription(groupName)} · ${cleanupRetentionEffect(row)}`;", source)
        self.assertNotIn('cleanup-detail-description-separator', source)
        self.assertNotIn('aria-hidden="true"> - </span>', source)
        self.assertNotIn('<h3 class="cleanup-detail-group">${esc(groupDisplay)}</h3>', source)
        self.assertNotIn('class="cleanup-detail-group"', source)
        self.assertIn("cleanupDetailSummaryItems(row, stats).map(([label, value]) => cleanupDefinitionItem(label, value)).join('')", source)
        self.assertNotIn("cleanupDefinitionItem('Affected Files', compactNumber(Number((stats || {}).affectedFiles || 0)))", source)
        self.assertIn("function cleanupCutoffDateLabel()", source)
        self.assertIn("compactDate(new Date(cutoff * 1000).toISOString())", source)
        self.assertNotIn("cleanupDefinitionItem('Delete Before', cleanupCutoffLabel())", source)
        self.assertNotIn("cleanupDefinitionItem(rowLabel, primaryValue, 'primary')", source)
        self.assertNotIn("function renderCleanupDetailContext(row, stats)", source)
        self.assertIn("function renderCleanupAffectedFileLedgerRows(row, files)", source)
        self.assertIn("const CLEANUP_AFFECTED_FILE_PAGE_SIZE = 25;", source)
        self.assertIn("cleanupDetailPage: 1", source)
        self.assertIn("function cleanupAffectedFilePageState(files)", source)
        self.assertIn("function renderCleanupAffectedFilePager(pageState)", source)
        self.assertIn("function setCleanupAffectedFilePage(page)", source)
        self.assertIn("function bindCleanupAffectedFilePager()", source)
        self.assertIn("function renderCleanupAffectedFileLedger(row, files, pageState = cleanupAffectedFilePageState(files))", source)
        self.assertIn("function renderCleanupAffectedFileLedgerHeader(row, affectedFiles, headerSummary = null)", source)
        self.assertNotIn("function cleanupAffectedFileUsesRows(row)", source)
        self.assertNotIn("function cleanupRowsLabel(rows)", source)
        self.assertNotIn("function cleanupAffectedFileMeasure(row, file)", source)
        self.assertNotIn("function cleanupAffectedFileLedgerMeasure(row, affectedFiles)", source)
        self.assertNotIn("function cleanupAffectedFileRowCount(row, file)", source)
        self.assertNotIn("if (summary.detailItemsKind === 'derived_outputs') return Number(retentionStatsForRow(row).deletableRows || 0);", source)
        self.assertNotIn("if (summary.detailItemsKind === 'direct_delete_files') return 1;", source)
        self.assertNotIn("detailItemsKind === 'direct_delete_files'", source)
        self.assertIn("summary.detailItemsKind === 'file_targets'", source)
        self.assertNotIn("text: '1 file'", source)
        self.assertNotIn("return `${compactNumber(affectedFiles.length)} ${affectedFiles.length === 1 ? 'file' : 'files'}`;", source)
        self.assertIn("function cleanupAffectedFileAction(row, file)", source)
        self.assertIn("if (summary.operation === '-') return '-';", source)
        self.assertIn("return '-';", source)
        self.assertNotIn("return 'Update';", source)
        self.assertIn("cleanup-affected-file-action", source)
        self.assertIn("function cleanupActionIcon(label)", source)
        self.assertIn('class="cleanup-affected-file-action-icon"', source)
        self.assertIn('aria-label="${esc(action)}"', source)
        self.assertIn('>${cleanupActionIcon(action)}</span>', source)
        self.assertNotIn('>${esc(action)}</span>', source)
        self.assertNotIn('cleanup-affected-file-number', source)
        self.assertIn("if (summary.detailItemsKind === 'derived_outputs') return 'Rebuild';", source)
        self.assertIn("const title = cleanupSummaryForRow(row).detailTitle || 'Affected Files';", source)
        self.assertNotIn("cleanup-affected-file-subtitle", source)
        self.assertIn("Affected Files", source)
        self.assertNotIn("Rebuild Inputs", source)
        self.assertNotIn("Files To Delete", source)
        self.assertNotIn("Rows Removed", source)
        self.assertIn("function updateCleanupFileSelection()", source)
        self.assertIn("function updateOpenCleanupDetailModal()", source)
        self.assertIn("updateOpenCleanupDetailModal();", source)
        self.assertIn("function openCleanupDetailModal(rowEl)", source)
        self.assertIn("row.addEventListener('dblclick'", source)
        self.assertNotIn("function updateCleanupFileDetail()", source)
        self.assertNotIn("function renderCleanupAffectedFileLedgerHeader(targets, deleteRows)", source)
        self.assertNotIn("function renderCleanupAffectedFileLedgerHeader(row, targets, deleteRows)", source)
        self.assertIn("const affectedFiles = cleanupDetailLedgerFilesForRow(detailRow);", source)
        self.assertNotIn("const title = cleanupRetentionRole(row) === 'derived_rebuild' ? 'Rebuild Inputs' : 'Deletion Targets';", source)
        self.assertNotIn("Deletion Targets", source)
        self.assertIn('No affected files.', source)
        self.assertNotIn('No files contain rows before the selected cutoff.', source)
        self.assertNotIn("renderCleanupFileTable(targets)", source)
        self.assertIn("const pageState = cleanupAffectedFilePageState(affectedFiles);", source)
        self.assertIn("renderCleanupAffectedFileLedger(detailRow, affectedFiles, pageState)", source)
        self.assertIn("function renderCleanupAffectedFileLedgerLoading(row, files, pageState = cleanupAffectedFilePageState(files), headerSummary = null)", source)
        self.assertIn("renderCleanupDetailSummary(row, stats)", source)
        self.assertIn("renderCleanupAffectedFileLedgerLoading(row, loading.files, loading.pageState, {affectedFileCount: loading.affectedFileCount})", source)
        self.assertNotIn("renderCleanupAffectedFilePager(loading.pageState)", source)
        self.assertNotIn("cleanupDefinitionItem('Action', cleanupSummaryForRow(row).operation, 'primary')", source)
        self.assertNotIn("cleanupDefinitionItem('Delete Size', formatBytes(cleanupSummaryForRow(row).deleteSize))", source)
        self.assertNotIn("cleanupDefinitionItem('Scope', cleanupSummaryForRow(row).scopeLabel)", source)
        self.assertIn('<div class="cleanup-detail-footer cleanup-detail-loading-footer" aria-hidden="true">', source)
        self.assertIn('<section class="cleanup-affected-file-ledger">', source)
        self.assertIn('<div class="cleanup-affected-file-list">${renderCleanupAffectedFileLedgerRows(row, pageState.pageFiles)}</div>', source)
        self.assertIn("${renderCleanupAffectedFilePager(pageState)}", source)
        self.assertNotIn("Use the main cleanup action to delete the full selected scope.", source)
        self.assertNotIn('cleanup-affected-file-pager" hidden', source)
        self.assertIn("data-cleanup-affected-file-page=", source)
        self.assertNotIn('<div class="cleanup-affected-file-list-head" aria-hidden="true">', source)
        self.assertIn("function cleanupSourceDirectory(path)", source)
        self.assertNotIn('<div class="label">Full Path</div>', source)
        self.assertIn("const path = String((file || {}).path || '');", source)
        self.assertIn("const fileName = cleanupSourceFileName(path);", source)
        self.assertIn("const directory = cleanupSourceDirectory(path);", source)
        self.assertIn("${esc(fileName)}", source)
        self.assertIn("${esc(directory)}", source)
        self.assertIn("${esc(kind)}", source)
        self.assertNotIn("${esc(measure.text)}", source)
        self.assertIn("let retentionDeleteSucceeded = false;", source)
        self.assertIn("document.getElementById('cleanup-confirm-delete').addEventListener('click', () => resolveCleanupConfirmModal(true));", source)
        self.assertIn("if (modal.dataset.busy === 'true') return;", source)
        self.assertIn("message: 'Deleting logs and rebuilding analysis'", source)
        self.assertIn("function startCleanupProgress(request)", source)
        self.assertIn("cleanupRequest = request;", source)
        self.assertIn("async function pollCleanupProgress(request)", source)
        self.assertIn("await getJSON('/api/log-cleanup/progress')", source)
        self.assertIn("applyCleanupProgress(progress, request);", source)
        self.assertIn("cleanupProgressTimer = setInterval(render, 1000);", source)
        self.assertIn("message: 'Refreshing dashboard data'", source)
        self.assertIn("message: 'Delete completed, refresh failed'", source)
        self.assertIn("message: `Deleted ${compactNumber(deletedRows)} rows`", source)
        self.assertIn("message: 'No logs to delete'", source)
        self.assertLess(source.index("message: 'No logs to delete'"), source.index("await postJSON('/api/log-cleanup/retention'"))
        self.assertIn("if (!cleanupHasRetentionWork()) {", source)
        self.assertNotIn("if (selectedRows <= 0) {", source)
        self.assertIn("message: `Deleted ${formatBytes(Number(result.deleted_bytes || 0))}`", source)
        self.assertIn("message: 'Delete changed data but cleanup failed'", source)
        self.assertIn("detail: `${formatBytes(deletedBytes)} were removed before the failure. Refresh cleanup data after resolving the error.`", source)
        self.assertIn("message: 'Delete failed'", source)
        self.assertNotIn("function cleanupDirectDeleteTarget(row)", source)
        self.assertNotIn("function cleanupDirectDeleteConfirmBody(row, summary, stats)", source)
        self.assertNotIn("body: cleanupDirectDeleteConfirmBody(row, summary, stats)", source)
        self.assertIn("const previewSignature = String((((state.cleanupRetention || {}).selected || {}).preview_signature) || '');", source)
        self.assertIn("q.set('preview_signature', previewSignature);", source)
        self.assertIn("function mergeCleanupDetailRow(row, detailRow)", source)
        self.assertIn("if (String((err || {}).code || '') === 'cleanup_preview_stale')", source)
        self.assertIn("Cleanup preview changed. Refreshing cleanup data.", source)
        self.assertIn("message: 'Cleanup preview changed'", source)
        self.assertNotIn('data-cleanup-direct-delete="${esc(directDeleteTarget)}"', source)
        self.assertNotIn("async function deleteCleanupFileGroup(target)", source)
        self.assertNotIn("await postJSON('/api/log-cleanup/delete', payload)", source)
        self.assertNotIn("if (target === 'tmp') payload.delete_tmp = true;", source)
        self.assertNotIn("if (target === 'bad') payload.delete_bad = true;", source)
        self.assertNotIn("event.target.closest('[data-cleanup-direct-delete]')", source)
        self.assertNotIn("setCleanupStatus(`deleted ${compactNumber(deletedRows)} old rows · rebuilt analysis`, 'success', 4000);", source)
        self.assertIn("modalButton.disabled = !retentionDeleteSucceeded;", source)
        self.assertIn('<span class="cleanup-affected-file-directory-label">Dir:</span>', source)
        self.assertNotIn('cleanup-affected-file-number-label', source)
        self.assertNotIn("Use the main cleanup action to delete the full selected scope.", source)
        self.assertNotIn('data-cleanup-modal-close="1"', source)
        self.assertNotIn('data-cleanup-modal-delete="1"', source)
        self.assertNotIn('style="width: ${esc(String(Math.round(oldRatioPct * 100) / 100))}%"', source)
        self.assertNotIn("const keptRows = Math.max(0, scannedRows - deleteRows);", source)
        self.assertNotIn('<div class="cleanup-affected-file-columns" aria-hidden="true">', source)
        self.assertNotIn('cleanup-file-group-kicker', source)
        self.assertNotIn('cleanup-file-source-item', source)
        self.assertNotIn('Selected File Group', source)
        self.assertNotIn('Files in Group', source)
        self.assertNotIn('cleanup-file-status', source)
        self.assertNotIn('Matches Cutoff', source)
        self.assertNotIn('No Old Rows', source)
        self.assertNotIn('Not Log Rows', source)
        self.assertIn("function cleanupPercent(value)", source)
        self.assertIn("cleanupDetailFilesForRow(row)", source)
        self.assertIn("source_size", source)
        self.assertIn("source_mtime_ns", source)
        self.assertNotIn("cleanupFileFact(", source)
        self.assertNotIn("function cleanupSourceType(row)", source)
        self.assertNotIn("detailMetric('Status', cleanupStatusLabel(row.status))", source)
        self.assertNotIn(".cleanup-summary-grid", source)
        self.assertNotIn("detailMetric('Deletable', formatBytes(summary.deletable_bytes || 0),", source)
        self.assertIn(".table-scroll:last-child tbody tr:last-child td {\n      border-bottom: 0;", source)

    def test_cleanup_retention_changes_disable_delete_until_preview_commits(self) -> None:
        source = dashboard_asset_bundle()
        cleanup_check = (ROOT / "scripts" / "playwright_dashboard_cleanup.py").read_text(encoding="utf-8")

        self.assertIn("function markCleanupPreviewUnavailable(message = 'Preview unavailable')", source)
        self.assertIn("markCleanupPreviewUnavailable('Preview loading');", source)
        self.assertIn("const expectedPreviewKey = cleanupPreviewKey();", source)
        self.assertIn("if (expectedPreviewKey !== cleanupPreviewKey()) return;", source)
        self.assertIn("state.cleanupRetentionAvailable = true;", source)
        self.assertLess(source.index("markCleanupPreviewUnavailable('Preview loading');"), source.index("loadCleanup({preserveRows: true});"))
        self.assertIn("def check_cleanup_preview_race(page, base_url: str) -> None:", cleanup_check)
        self.assertIn("check_cleanup_preview_race(page, base_url)", cleanup_check)
        self.assertIn('page.route("**/api/log-cleanup?*"', cleanup_check)
        self.assertIn('assert_true(delete_button.is_disabled()', cleanup_check)
